### ISSUE TITLE
How to send attachments?

### ISSUE THREAD

**Issue by optikfluffel** [chrismccord/mailgun#27]
Hi :)
It would be nice to have an example (or test case to look at) on how to send an email with some files attached.

**Comment by vysakh0** [comment]
@optikfluffel  We could send multiple attachments as a list of maps (even keyword list) with keys `path` & `filename`

```elixir
def send_greetings(user, file_path) do
    send_email to: user.email,
               from: @from,
               subject: "Happy b'day",
               html: "<strong>Cheers!</strong>"
               attachments: [%{path: file_path, filename: "greetings.png"}]
end
```

In my case I wanted to send invoice pdf on the fly in my mails to users, so didn't want to create a temporary file and send it part of the `attachments`. So, did this https://github.com/vysakh0/mailgun/commit/4f64da915bd52eb7358fdb0eabc1d209b0f13628

**Comment by optikfluffel** [comment]
@vysakh0 cool, thanks a ton, I also wanted to send something without writing it to disk first, perfect! :grin: 
I wonder if you should make a PR to make this a feature, I'm not sure wether we're the only ones wanting to send attachments this way or not.
Any thoughts on this @chrismccord?

**Comment by chrismccord** [comment]
yes, PR please!

**Comment by vysakh0** [comment]
Thanks :+1: Done :smile: https://github.com/chrismccord/mailgun/pull/28

**Comment by tralamazza** [comment]
Anyone tried sending binary attachments, like a pdf for instance? I'm having trouble.

httpc seems stuck while trying to send a pdf. (using 0.1.2)
