### ISSUE TITLE
poison dependency conflicts with other package

### ISSUE THREAD

**Issue by hdcos** [chrismccord/mailgun#37]
Hello I created an api for a webservice but when I try to import it in my phoenix application I have the following error message:

    Conflict on poison 2.0.1
      /home/me/Projects/elixir/lemonwex/mix.exs: 2.0.1
      mailgun 0.1.2: ~> 1.4

    ** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

The project lemonwex uses poison 2.0.1 internally. I don't understand why it conflicts with the one mailgun uses. How can I fix this? I quick fixed this by retrograding the version to 1.5.2 so that mailgun doesn't conflict but there is certainly a better way

**Comment by chrismccord** [comment]
You can override it with `{:poison, "~> 2.0", override; true}`
